export const countries = [
  { name: "Afghanistan", flag: "🇦🇫", code: "+93" },
  { name: "Afrique du Sud", flag: "🇿🇦", code: "+27" },
  { name: "Albanie", flag: "🇦🇱", code: "+355" },
  { name: "Algérie", flag: "🇩🇿", code: "+213" },
  { name: "Allemagne", flag: "🇩🇪", code: "+49" },
  { name: "Andorre", flag: "🇦🇩", code: "+376" },
  { name: "Angola", flag: "🇦🇴", code: "+244" },
  { name: "Antigua-et-Barbuda", flag: "🇦🇬", code: "+1-268" },
  { name: "Arabie Saoudite", flag: "🇸🇦", code: "+966" },
  { name: "Argentine", flag: "🇦🇷", code: "+54" },
  { name: "Arménie", flag: "🇦🇲", code: "+374" },
  { name: "Australie", flag: "🇦🇺", code: "+61" },
  { name: "Autriche", flag: "🇦🇹", code: "+43" },
  { name: "Azerbaïdjan", flag: "🇦🇿", code: "+994" },
  { name: "Bahamas", flag: "🇧🇸", code: "+1-242" },
  { name: "Bahreïn", flag: "🇧🇭", code: "+973" },
  { name: "Bangladesh", flag: "🇧🇩", code: "+880" },
  { name: "Barbade", flag: "🇧🇧", code: "+1-246" },
  { name: "Belgique", flag: "🇧🇪", code: "+32" },
  { name: "Belize", flag: "🇧🇿", code: "+501" },
  { name: "Bénin", flag: "🇧🇯", code: "+229" },
  { name: "Bhoutan", flag: "🇧🇹", code: "+975" },
  { name: "Biélorussie", flag: "🇧🇾", code: "+375" },
  { name: "Birmanie (Myanmar)", flag: "🇲🇲", code: "+95" },
  { name: "Bolivie", flag: "🇧🇴", code: "+591" },
  { name: "Bosnie-Herzégovine", flag: "🇧🇦", code: "+387" },
  { name: "Botswana", flag: "🇧🇼", code: "+267" },
  { name: "Brésil", flag: "🇧🇷", code: "+55" },
  { name: "Brunei", flag: "🇧🇳", code: "+673" },
  { name: "Bulgarie", flag: "🇧🇬", code: "+359" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "+226" },
  { name: "Burundi", flag: "🇧🇮", code: "+257" },
  { name: "Cambodge", flag: "🇰🇭", code: "+855" },
  { name: "Cameroun", flag: "🇨🇲", code: "+237" },
  { name: "Canada", flag: "🇨🇦", code: "+1" },
  { name: "Cap-Vert", flag: "🇨🇻", code: "+238" },
  { name: "Chili", flag: "🇨🇱", code: "+56" },
  { name: "Chine", flag: "🇨🇳", code: "+86" },
  { name: "Chypre", flag: "🇨🇾", code: "+357" },
  { name: "Colombie", flag: "🇨🇴", code: "+57" },
  { name: "Comores", flag: "🇰🇲", code: "+269" },
  { name: "Congo (Brazzaville)", flag: "🇨🇬", code: "+242" },
  { name: "Congo (Kinshasa)", flag: "🇨🇩", code: "+243" },
  { name: "Corée du Nord", flag: "🇰🇵", code: "+850" },
  { name: "Corée du Sud", flag: "🇰🇷", code: "+82" },
  { name: "Costa Rica", flag: "🇨🇷", code: "+506" },
  { name: "Côte d'Ivoire", flag: "🇨🇮", code: "+225" },
  { name: "Croatie", flag: "🇭🇷", code: "+385" },
  { name: "Cuba", flag: "🇨🇺", code: "+53" },
  { name: "Danemark", flag: "🇩🇰", code: "+45" },
  { name: "Djibouti", flag: "🇩🇯", code: "+253" },
  { name: "Égypte", flag: "🇪🇬", code: "+20" },
  { name: "Émirats arabes unis", flag: "🇦🇪", code: "+971" },
  { name: "Équateur", flag: "🇪🇨", code: "+593" },
  { name: "Érythrée", flag: "🇪🇷", code: "+291" },
  { name: "Espagne", flag: "🇪🇸", code: "+34" },
  { name: "Estonie", flag: "🇪🇪", code: "+372" },
  { name: "Eswatini", flag: "🇸🇿", code: "+268" },
  { name: "États-Unis", flag: "🇺🇸", code: "+1" },
  { name: "Éthiopie", flag: "🇪🇹", code: "+251" },
  { name: "Fidji", flag: "🇫🇯", code: "+679" },
  { name: "Finlande", flag: "🇫🇮", code: "+358" },
  { name: "France", flag: "🇫🇷", code: "+33" },
  { name: "Gabon", flag: "🇬🇦", code: "+241" },
  { name: "Gambie", flag: "🇬🇲", code: "+220" },
  { name: "Géorgie", flag: "🇬🇪", code: "+995" },
  { name: "Ghana", flag: "🇬🇭", code: "+233" },
  { name: "Grèce", flag: "🇬🇷", code: "+30" },
  { name: "Grenade", flag: "🇬🇩", code: "+1-473" },
  { name: "Guatemala", flag: "🇬🇹", code: "+502" },
  { name: "Guinée", flag: "🇬🇳", code: "+224" },
  { name: "Guinée équatoriale", flag: "🇬🇶", code: "+240" },
  { name: "Guinée-Bissau", flag: "🇬🇼", code: "+245" },
  { name: "Guyana", flag: "🇬🇾", code: "+592" },
  { name: "Haïti", flag: "🇭🇹", code: "+509" },
  { name: "Honduras", flag: "🇭🇳", code: "+504" },
  { name: "Hongrie", flag: "🇭🇺", code: "+36" },
  { name: "Inde", flag: "🇮🇳", code: "+91" },
  { name: "Indonésie", flag: "🇮🇩", code: "+62" },
  { name: "Irak", flag: "🇮🇶", code: "+964" },
  { name: "Iran", flag: "🇮🇷", code: "+98" },
  { name: "Irlande", flag: "🇮🇪", code: "+353" },
  { name: "Islande", flag: "🇮🇸", code: "+354" },
  { name: "Israël", flag: "🇮🇱", code: "+972" },
  { name: "Italie", flag: "🇮🇹", code: "+39" },
  { name: "Jamaïque", flag: "🇯🇲", code: "+1-876" },
  { name: "Japon", flag: "🇯🇵", code: "+81" },
  { name: "Jordanie", flag: "🇯🇴", code: "+962" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "+7" },
  { name: "Kenya", flag: "🇰🇪", code: "+254" },
  { name: "Kirghizistan", flag: "🇰🇬", code: "+996" },
  { name: "Koweït", flag: "🇰🇼", code: "+965" },
  { name: "Laos", flag: "🇱🇦", code: "+856" },
  { name: "Lesotho", flag: "🇱🇸", code: "+266" },
  { name: "Lettonie", flag: "🇱🇻", code: "+371" },
  { name: "Liban", flag: "🇱🇧", code: "+961" },
  { name: "Liberia", flag: "🇱🇷", code: "+231" },
  { name: "Libye", flag: "🇱🇾", code: "+218" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "+423" },
  { name: "Lituanie", flag: "🇱🇹", code: "+370" },
  { name: "Luxembourg", flag: "🇱🇺", code: "+352" },
  { name: "Macédoine du Nord", flag: "🇲🇰", code: "+389" },
  { name: "Madagascar", flag: "🇲🇬", code: "+261" },
  { name: "Malaisie", flag: "🇲🇾", code: "+60" },
  { name: "Malawi", flag: "🇲🇼", code: "+265" },
  { name: "Maldives", flag: "🇲🇻", code: "+960" },
  { name: "Mali", flag: "🇲🇱", code: "+223" },
  { name: "Malte", flag: "🇲🇹", code: "+356" },
  { name: "Maroc", flag: "🇲🇦", code: "+212" },
  { name: "Maurice", flag: "🇲🇺", code: "+230" },
  { name: "Mauritanie", flag: "🇲🇷", code: "+222" },
  { name: "Mexique", flag: "🇲🇽", code: "+52" },
  { name: "Moldavie", flag: "🇲🇩", code: "+373" },
  { name: "Monaco", flag: "🇲🇨", code: "+377" },
  { name: "Mongolie", flag: "🇲🇳", code: "+976" },
  { name: "Monténégro", flag: "🇲🇪", code: "+382" },
  { name: "Mozambique", flag: "🇲🇿", code: "+258" },
  { name: "Namibie", flag: "🇳🇦", code: "+264" },
  { name: "Népal", flag: "🇳🇵", code: "+977" },
  { name: "Nicaragua", flag: "🇳🇮", code: "+505" },
  { name: "Niger", flag: "🇳🇪", code: "+227" },
  { name: "Nigeria", flag: "🇳🇬", code: "+234" },
  { name: "Norvège", flag: "🇳🇴", code: "+47" },
  { name: "Nouvelle-Zélande", flag: "🇳🇿", code: "+64" },
  { name: "Oman", flag: "🇴🇲", code: "+968" },
  { name: "Ouganda", flag: "🇺🇬", code: "+256" },
  { name: "Ouzbékistan", flag: "🇺🇿", code: "+998" },
  { name: "Pakistan", flag: "🇵🇰", code: "+92" },
  { name: "Panama", flag: "🇵🇦", code: "+507" },
  { name: "Paraguay", flag: "🇵🇾", code: "+595" },
  { name: "Pays-Bas", flag: "🇳🇱", code: "+31" },
  { name: "Pérou", flag: "🇵🇪", code: "+51" },
  { name: "Philippines", flag: "🇵🇭", code: "+63" },
  { name: "Pologne", flag: "🇵🇱", code: "+48" },
  { name: "Portugal", flag: "🇵🇹", code: "+351" },
  { name: "Qatar", flag: "🇶🇦", code: "+974" },
  { name: "République centrafricaine", flag: "🇨🇫", code: "+236" },
  { name: "République dominicaine", flag: "🇩🇴", code: "+1-809" },
  { name: "République tchèque", flag: "🇨🇿", code: "+420" },
  { name: "Roumanie", flag: "🇷🇴", code: "+40" },
  { name: "Royaume-Uni", flag: "🇬🇧", code: "+44" },
  { name: "Russie", flag: "🇷🇺", code: "+7" },
  { name: "Rwanda", flag: "🇷🇼", code: "+250" },
  { name: "Salvador", flag: "🇸🇻", code: "+503" },
  { name: "Samoa", flag: "🇼🇸", code: "+685" },
  { name: "Sao Tomé-et-Principe", flag: "🇸🇹", code: "+239" },
  { name: "Sénégal", flag: "🇸🇳", code: "+221" },
  { name: "Serbie", flag: "🇷🇸", code: "+381" },
  { name: "Seychelles", flag: "🇸🇨", code: "+248" },
  { name: "Sierra Leone", flag: "🇸🇱", code: "+232" },
  { name: "Singapour", flag: "🇸🇬", code: "+65" },
  { name: "Slovaquie", flag: "🇸🇰", code: "+421" },
  { name: "Slovénie", flag: "🇸🇮", code: "+386" },
  { name: "Somalie", flag: "🇸🇴", code: "+252" },
  { name: "Soudan", flag: "🇸🇩", code: "+249" },
  { name: "Soudan du Sud", flag: "🇸🇸", code: "+211" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "+94" },
  { name: "Suède", flag: "🇸🇪", code: "+46" },
  { name: "Suisse", flag: "🇨🇭", code: "+41" },
  { name: "Suriname", flag: "🇸🇷", code: "+597" },
  { name: "Syrie", flag: "🇸🇾", code: "+963" },
  { name: "Tadjikistan", flag: "🇹🇯", code: "+992" },
  { name: "Tanzanie", flag: "🇹🇿", code: "+255" },
  { name: "Tchad", flag: "🇹🇩", code: "+235" },
  { name: "Thaïlande", flag: "🇹🇭", code: "+66" },
  { name: "Togo", flag: "🇹🇬", code: "+228" },
  { name: "Tonga", flag: "🇹🇴", code: "+676" },
  { name: "Trinité-et-Tobago", flag: "🇹🇹", code: "+1-868" },
  { name: "Tunisie", flag: "🇹🇳", code: "+216" },
  { name: "Turkménistan", flag: "🇹🇲", code: "+993" },
  { name: "Turquie", flag: "🇹🇷", code: "+90" },
  { name: "Tuvalu", flag: "🇹🇻", code: "+688" },
  { name: "Ukraine", flag: "🇺🇦", code: "+380" },
  { name: "Uruguay", flag: "🇺🇾", code: "+598" },
  { name: "Vanuatu", flag: "🇻🇺", code: "+678" },
  { name: "Vatican", flag: "🇻🇦", code: "+379" },
  { name: "Venezuela", flag: "🇻🇪", code: "+58" },
  { name: "Viêt Nam", flag: "🇻🇳", code: "+84" },
  { name: "Yémen", flag: "🇾🇪", code: "+967" },
  { name: "Zambie", flag: "🇿🇲", code: "+260" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "+263" }
];
